services:
  api:
    build: .
    image: abhisakh/events-api
    container_name: events-container
    ports:
      - "4000:4000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=4000